从社区最新版本合并代码
没有包括Ora2Pg.pm

diff --git a/scripts/ora2pg b/scripts/ora2pg
--- a/scripts/ora2pg
+++ b/scripts/ora2pg
@@ -31,7 +31,7 @@ use POSIX qw(locale_h sys_wait_h _exit);
 setlocale(LC_NUMERIC, '');
 setlocale(LC_ALL,     'C');
 
-my $VERSION = '18.1';
+my $VERSION = '18.2';
 
 $| = 1;
 
@@ -84,14 +84,14 @@ my $WHERE_OPTION = '';
 # end by jiangmj3
 my $DATA_TYPE = '';
 my $GRANT_OBJECT = '';
-
-
+my $PG_SCHEMA = '';
+my $NO_HEADER = 0;
 
 
 my @SCHEMA_ARRAY  = qw( TABLE PACKAGE VIEW GRANT SEQUENCE TRIGGER FUNCTION PROCEDURE TABLESPACE PARTITION TYPE MVIEW DBLINK SYNONYM DIRECTORY );
 my @EXTERNAL_ARRAY  = qw( KETTLE FDW );
 my @REPORT_ARRAY  = qw( SHOW_VERSION SHOW_REPORT SHOW_SCHEMA SHOW_TABLE SHOW_COLUMN SHOW_ENCODING  );
-my @TEST_ARRAY  = qw( TEST );
+my @TEST_ARRAY  = qw( TEST TEST_VIEW);
 my @SOURCES_ARRAY = qw( PACKAGE VIEW TRIGGER FUNCTION PROCEDURE PARTITION TYPE MVIEW );
 my @DATA_ARRAY    = qw( INSERT COPY );
 my @CAPABILITIES  = qw( QUERY LOAD );
@@ -132,6 +132,7 @@ GetOptions (
 	'u|user=s' => \$DBUSER,
 	'w|password=s' => \$DBPWD,
 	'n|namespace=s' => \$SCHEMA,
+	'N|pg_schema=s' => \$PG_SCHEMA,
 	'x|xtable=s' => \$TABLEONLY, # Obsolete
 	'forceowner=s' => \$FORCEOWNER,
 	'nls_lang=s' => \$ORA_ENCODING,
@@ -151,11 +152,12 @@ GetOptions (
 	'pg_user=s' => \$PG_USER,
 	'pg_pwd=s' => \$PG_PWD,
 	'count_rows!' => \$COUNT_ROWS,
+	'no_header!' => \$NO_HEADER,
 );
 
 # Check command line parameters
 if ($SHOW_VER) {
-	print "Ora2Pg for ADB v$VERSION\n";
+	print "Ora2Pg for AntDB v$VERSION\n";
 	exit 0;
 }
 if ($HELP) {
@@ -199,10 +201,13 @@ closedir DIR;
 #}
 
 # Check configuration file
+my $GOES_WITH_DEFAULT = 0;
 if ($FILE_CONF && ! -e $FILE_CONF) {
 	print "FATAL: can't find configuration file $FILE_CONF\n";
 	&usage();
 } elsif (!$FILE_CONF && ! -e $CONFIG_FILE) {
+	# At least we need configuration to connect to Oracle
+	if (!$DSN || (!$DBUSER && !$ENV{ORA2PG_USER}) || (!$DBPWD && !$ENV{ORA2PG_PASSWD})) {
 	print "FATAL: can't find configuration file $CONFIG_FILE\n";
 	&usage();
 }
@@ -304,6 +309,7 @@ my $schema = new Ora2Pg (
         user => $DBUSER || $ENV{ORA2PG_USER},
         password => $DBPWD || $ENV{ORA2PG_PASSWD},
 	schema => $SCHEMA,
+	pg_schema => $PG_SCHEMA,
 	force_owner => $FORCEOWNER,
         nls_lang => $ORA_ENCODING,
         client_encoding => $PG_ENCODING,
@@ -332,8 +338,28 @@ my $schema = new Ora2Pg (
 	count_rows => $COUNT_ROWS,
 	data_type => $DATA_TYPE,
 	grant_object => $GRANT_OBJECT,
+	no_header => $NO_HEADER,
 );
 
+# Look at configuration file if an input file is defined
+if (!$INPUT_FILE && !$GOES_WITH_DEFAULT) {
+	my $cf_file = $FILE_CONF || $CONFIG_FILE;
+	my $fh = new IO::File;
+	$fh->open($cf_file) or die "FATAL: can't read configuration file $cf_file, $!\n";
+	while (my $l = <$fh>) {
+		chomp($l);
+		$l =~ s/\r//gs;
+		$l =~ s/^\s*\#.*$//g;
+		next if (!$l || ($l =~ /^\s+$/));
+		$l =~ s/^\s*//; $l =~ s/\s*$//;
+		my ($var, $val) = split(/\s+/, $l, 2);
+		$var = uc($var);
+		if ($var eq 'INPUT_FILE' && $val) {
+			$INPUT_FILE = $val;
+		}
+	}
+	$fh->close();
+}
 
 # Proceed to Oracle DB extraction following
 # configuration file definitions.
@@ -363,15 +389,15 @@ sub usage
 	print qq{
 Usage: ora2pg [-dhpqv --estimate_cost --dump_as_html] [--option value]
 
-    -a | --allow str  : coma separated list of objects to allow from export.
+    -a | --allow str  : Comma separated list of objects to allow from export.
 			Can be used with SHOW_COLUMN too.
-    -b | --basedir dir: Used to set the default output directory, where files
+    -b | --basedir dir: Set the default output directory, where files
 			resulting from exports will be stored.
-    -c | --conf file  : Used to set an alternate configuration file than the
+    -c | --conf file  : Set an alternate configuration file other than the
 			default /etc/ora2pg/ora2pg.conf.
     -d | --debug      : Enable verbose output.
     -D | --data_type STR : Allow custom type replacement at command line.
-    -e | --exclude str: coma separated list of objects to exclude from export.
+    -e | --exclude str: Comma separated list of objects to exclude from export.
 			Can be used with SHOW_COLUMN too.
     -h | --help       : Print this short help.
     -g | --grant_object type : extract privilege from the given object type.
@@ -380,35 +406,36 @@ Usage: ora2pg [-dhpqv --estimate_cost --dump_as_html] [--option value]
 			no Oracle database connection initiated.
     -j | --jobs num   : number of parallel process to send data to PostgreSQL.
     -J | --copies num : number of parallel connection to extract data from Oracle.
-    -l | --log file   : Used to set a log file. Default is stdout.
+    -l | --log file   : Set a log file. Default is stdout.
     -L | --limit num  : number of tuples extracted from Oracle and stored in
 			memory before writing, default: 10000.
     -m | --mysql      : Export a MySQL database instead of an Oracle schema.
-    -n | --namespace schema : Used to set the Oracle schema to extract from.
-    -o | --out file   : Used to set the path to the output file where SQL will
+    -n | --namespace schema : Set the Oracle schema to extract from.
+    -N | --pg_schema schema : Set PostgreSQL's search_path.
+    -o | --out file   : Set the path to the output file where SQL will
 			be written. Default: output.sql in running directory.
-    -p | --plsql      : Enable PLSQL to PLPSQL code conversion.
+    -p | --plsql      : Enable PLSQL to PLPGSQL code conversion.
     -P | --parallel num: Number of parallel tables to extract at the same time.
     -q | --quiet      : disable progress bar.
-	-r | --distribute_by_mode mode: table distribute by replication or ROUNDROBIN.
-	-W | --where_option: Allow to set the filter condition.
+    -r | --distribute_by_mode mode: table distribute by replication or ROUNDROBIN.（by AntDB）
+    -W | --where_option: Allow to set the filter condition.（by AntDB）
     -s | --source DSN : Allow to set the Oracle DBI datasource.
-    -t | --type export: Used to set the export type. It will override the one
+    -t | --type export: Set the export type. It will override the one
 			given in the configuration file (TYPE).
-    -T | --temp_dir DIR: use it to set a distinct temporary directory when two
+    -T | --temp_dir DIR: Set a distinct temporary directory when two
                          or more ora2pg are run in parallel.
-    -u | --user name  : Used to set the Oracle database connection user.
+    -u | --user name  : Set the Oracle database connection user.
 		        ORA2PG_USER environment variable can be used instead.
     -v | --version    : Show Ora2Pg Version and exit.
-    -w | --password pwd : Used to set the password of the Oracle database user.
+    -w | --password pwd : Set the password of the Oracle database user.
 		        ORA2PG_PASSWD environment variable can be used instead.
-    --forceowner: if set to 1 force ora2pg to set tables and sequences owner
-		  like in Oracle database. If the value is set to a username this
-		  one will be used as the objects owner. By default it's the user
+    --forceowner      : Force ora2pg to set tables and sequences owner like in
+		  Oracle database. If the value is set to a username this one
+		  will be used as the objects owner. By default it's the user
 		  used to connect to the Pg database that will be the owner.
-    --nls_lang code: use this to set the Oracle NLS_LANG client encoding.
-    --client_encoding code: Use this to set the PostgreSQL client encoding.
-    --view_as_table str: coma separated list of view to export as table.
+    --nls_lang code: Set the Oracle NLS_LANG client encoding.
+    --client_encoding code: Set the PostgreSQL client encoding.
+    --view_as_table str: Comma separated list of view to export as table.
     --estimate_cost   : activate the migration cost evalution with SHOW_REPORT
     --cost_unit_value minutes: number of minutes for a cost evalution unit.
 		  default: 5 minutes, correspond to a migration conducted by a
@@ -421,7 +448,7 @@ Usage: ora2pg [-dhpqv --estimate_cost --dump_as_html] [--option value]
                         will be created under project base dir.
    --project_base DIR : define the base dir for ora2pg project trees. Default
                         is current directory.
-   --print_header     : to be used with --dump_as_sheet to print the CSV header
+   --print_header     : Used with --dump_as_sheet to print the CSV header
                         especially for the first run of ora2pg.
    --human_days_limit num : set the number human-days limit where the migration
                         assessment level switch from B to C. Default is set to
@@ -433,14 +460,15 @@ Usage: ora2pg [-dhpqv --estimate_cost --dump_as_html] [--option value]
    --pg_user name     : set the PostgreSQL user to use.
    --pg_pwd password  : set the PostgreSQL password to use.
    --count_rows       : force ora2pg to perform a real row count in TEST action.
+   --no_header        : Do not append Ora2Pg header to output file
 
 See full documentation at http://ora2pg.darold.net/ for more help or see
 manpage with 'man ora2pg'.
 
 ora2pg will return 0 on success, 1 on error. It will return 2 when a child
-process have been interrupted and you've got the warning message:
+process has been interrupted and you've gotten the warning message:
     "WARNING: an error occurs during data export. Please check what's happen."
-Most of the time this is an OOM issue, you might first reduce DATA_LIMIT value.
+Most of the time this is an OOM issue, first try reducing DATA_LIMIT value.
 
 };
 	exit 1;
@@ -618,6 +646,7 @@ sub make_config_generic
 		$conf_arr->[$i] =~ s/^PLSQL_PGSQL.*1/PLSQL_PGSQL\t0/;
 		$conf_arr->[$i] =~ s/^FILE_PER_CONSTRAINT.*0/FILE_PER_CONSTRAINT\t1/;
 		$conf_arr->[$i] =~ s/^FILE_PER_INDEX.*0/FILE_PER_INDEX\t1/;
+		$conf_arr->[$i] =~ s/^FILE_PER_FKEYS.*0/FILE_PER_FKEYS\t1/;
 		$conf_arr->[$i] =~ s/^FILE_PER_TABLE.*0/FILE_PER_TABLE\t1/;
 		$conf_arr->[$i] =~ s/^FILE_PER_FUNCTION.*0/FILE_PER_FUNCTION\t1/;
 		$conf_arr->[$i] =~ s/^TRUNCATE_TABLE.*0/TRUNCATE_TABLE\t1/;
@@ -629,6 +658,7 @@ sub make_config_generic
 		$conf_arr->[$i] =~ s/^AUTODETECT_SPATIAL_TYPE.*0/AUTODETECT_SPATIAL_TYPE\t1/;
 		$conf_arr->[$i] =~ s/^NO_LOB_LOCATOR.*/NO_LOB_LOCATOR\t0/;
 		$conf_arr->[$i] =~ s/^FTS_INDEX_ONLY.*0/FTS_INDEX_ONLY\t1/;
+		$conf_arr->[$i] =~ s/^DISABLE_UNLOGGED.*0/DISABLE_UNLOGGED\t1/;
 		if ($DSN) {
 			$conf_arr->[$i] =~ s/^ORACLE_DSN.*/ORACLE_DSN\t$DSN/;
 		}
@@ -776,6 +806,27 @@ import_constraints () {
 		fi
 	fi
 
+	if [ -r "$NAMESPACE/schema/tables/FKEYS_table.sql" ]; then
+		if confirm "Would you like to import foreign keys from $NAMESPACE/schema/tables/FKEYS_table.sql?" ; then
+			if [ -z "$IMPORT_JOBS" ]; then
+				echo "Running: psql$DB_HOST$DB_PORT -U $DB_OWNER -d $DB_NAME -f $NAMESPACE/schema/tables/FKEYS_table.sql"
+				if [ $DEBUG -eq 0 ]; then
+					psql$DB_HOST$DB_PORT -U $DB_OWNER -d $DB_NAME -f $NAMESPACE/schema/tables/FKEYS_table.sql
+					if [ $? -ne 0 ]; then
+						die "can not import foreign keys."
+					fi
+				fi
+			else
+				echo "Running: ora2pg$IMPORT_JOBS -c config/ora2pg.conf -t LOAD -i $NAMESPACE/schema/tables/FKEYS_table.sql"
+				if [ $DEBUG -eq 0 ]; then
+					ora2pg$IMPORT_JOBS -c config/ora2pg.conf -t LOAD -i $NAMESPACE/schema/tables/FKEYS_table.sql
+					if [ $? -ne 0 ]; then
+						die "can not import foreign keys."
+					fi
+				fi
+			fi
+		fi
+	fi
 	if [ $NO_CONSTRAINTS -eq 1 ] && [ -r "$NAMESPACE/schema/triggers/trigger.sql" ]; then
 		if confirm "Would you like to import TRIGGER from $NAMESPACE/schema/triggers/trigger.sql?" ; then
 			echo "Running: psql --single-transaction$DB_HOST$DB_PORT -U $DB_OWNER -d $DB_NAME -f $NAMESPACE/schema/triggers/trigger.sql"
@@ -809,8 +860,8 @@ while getopts "b:d:e:h:j:l:n:o:p:P:t:r:W:U:aDfiIsyx?"  opt; do
         P) PARALLEL_TABLES=" -P $OPTARG";;
         s) SCHEMA_ONLY=1;;
         t) EXPORT_TYPE=$OPTARG;;
-		r) DISTRIBUTE_BY_MODE=$OPTARG;;
-		W) WHERE_OPTION=$OPTARG;;
+	r) DISTRIBUTE_BY_MODE=$OPTARG;;
+	W) WHERE_OPTION=$OPTARG;;
         U) DB_USER=" -U $OPTARG";;
 	x) IMPORT_INDEXES_AFTER=1;;
         y) AUTORUN=1;;
@@ -853,7 +904,7 @@ fi
 if [ $DATA_ONLY -eq 0 ]; then
 	if [ $NO_DBCHECK  -eq 0 ]; then
 		# Create owner user
-		user_exists=`psql$DB_HOST$DB_PORT$DB_USER -Atc "select usename from pg_user where usename='$DB_OWNER';"`
+    user_exists=`psql -d $DB_NAME$DB_HOST$DB_PORT$DB_USER -Atc "select usename from pg_user where usename='$DB_OWNER';"`
 		if [ "a$user_exists" = "a" ]; then
 			if confirm "Would you like to create the owner of the database $DB_OWNER?" ; then
 				echo "Running: createuser$DB_HOST$DB_PORT$DB_USER --no-superuser --no-createrole --no-createdb $DB_OWNER"
@@ -872,7 +923,7 @@ if [ $DATA_ONLY -eq 0 ]; then
 		if [ "a$DB_ENCODING" = "a" ]; then
 			DB_ENCODING=" -E UTF8"
 		fi
-		db_exists=`psql$DB_HOST$DB_PORT$DB_USER -Atc "select datname from pg_database where datname='$DB_NAME';"`
+    db_exists=`psql -d $DB_NAME$DB_HOST$DB_PORT$DB_USER -Atc "select datname from pg_database where datname='$DB_NAME';"`
 		if [ "a$db_exists" = "a" ]; then
 			if confirm "Would you like to create the database $DB_NAME?" ; then
 				echo "Running: createdb$DB_HOST$DB_PORT$DB_USER$DB_ENCODING --owner $DB_OWNER $DB_NAME"
@@ -1016,7 +1067,8 @@ if [ $SCHEMA_ONLY -eq 0 ]; then
 		if [ "a$DB_HOST" != "a" ]; then
 			pgdsn_defined="dbi:Pg:dbname=$DB_NAME;host=$DB_HOST"
 		else
-			pgdsn_defined="dbi:Pg:dbname=$DB_NAME;host=localhost"
+      #default to unix socket
+      pgdsn_defined="dbi:Pg:dbname=$DB_NAME;"
 		fi
 		if [ "a$DB_PORT" != "a" ]; then
 			pgdsn_defined="$pgdsn_defined;port=$DB_PORT"
